# Site settings
title: 'Yet another possibility'  # Your Title
tagline: '有约如铁'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown

# Personal info
avatar: ./images/avatar.png
photo: ./images/tequila-sunrise.jpg
email: yanshisangc@gmail.com
github: https://github.com/fakeYanss
blog: /blog
til: /til
ins: /gallery
about: /blog/about

# Logo setting
logocolor: '#000'
