# Site settings
title: 'Yet another possibility'  # Your Title
tagline: '有约如铁'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: https://github.com/zchen9/code/issues
fragmenturl: /blog/

# Personal info
avatar: ./images/avatar.png
photo: ./images/hey.jpg
email: yanshisangc@gmail.com
github: https://github.com/fakeYanss
twitter: https://twitter.com/fakeYanss
ins: https://foreti.me/gallery/

# Logo setting
logocolor: '#000'
